from __future__ import annotations

from typing import Protocol

from petbot.domain.face.face_state import Expression, Gaze, MouthState


class FaceDisplay(Protocol):
    def set_expression(self, expression: Expression) -> None: ...
    def blink(self) -> None: ...
    def wink_left(self) -> None: ...
    def wink_right(self) -> None: ...
    def look_at(self, gaze: Gaze) -> None: ...
    def set_mouth_state(self, mouth: MouthState) -> None: ...
    def speak_animation(self, duration_ms: int = 1_000) -> None: ...
    def sleep(self) -> None: ...
    def wake(self) -> None: ...
